/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'EX352152' at '21/12/16 14:35' with Gradle 3.2.1
 *
 * @author EX352152, @date 21/12/16 14:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
